// System verilog architecture
/*
System verilog test bench contain TEST TOP
  -  Inside the TEST TOP it contain two components
      1) TEST and DUT
          *  Whatever signals coming from the TEST is sending to DUT through INTERFACE(it is an full duplex).
      
      2) Inside the test their contains one ENVIRONMENT. this ENVIRONMENT consist of two things
          1) GENERATOR
          2) DRIVER
          3) SCOREBOARD
          4) MONITOR
  -  
  -> Components
      1) INTERFACE: Act as an communicator from the test bench to Design under test(DUT).
      2) GENERATOR: It generate some random data which is required for DUT, input signal required for the DUT is send by GENERATOR.
      3) TRANSACTION: It contain bunch of data generated by GENERATOR.through MAIL BOX concept we are sending the data from GENERATOR to DRIVER. 
      4) DRIVER: The data generated inside the GENERATOR is not directly sending to DUT, first data from the generator is sending to DRIVER via INTERFACE to the DUT.
      
      
- ARCHITECTURE FLOW
    -  GENERATOR produces the data -> through TRANSACTION(uses MAIL BOX concept to send data) it send data to DRIVER ---> through INTERFACE it send the data to the DUT ---> 
    after computation DUT send the data back to the MONITOR
*/
